### ISSUE TITLE
local stream not displaying 

### ISSUE THREAD

**Issue by bobemoe** [TomasValenta/WebCamViewer#3]
I have a foscam camera on the lan but it doesn't load. It just shows a cloud Icon with an exclamation mark in it. URL is http://192.168.1.108:88/cgi-bin/CGIStream.cgi?cmd=GetMJStream&usr=xxxx&pwd=xxxx

VLC shows the local stream fine so the url and connectivity is ok. 

The remote streams imported from the default servers play ok too.

**Comment by TomasValenta** [comment]
Ok, thank you for this report. I am currently out of work. As soon as I can, I look at it!

**Comment by TomasValenta** [comment]
Hi,
I looked at your URL and the problem is with the stream type. In this moment WebCam Viewer support only static images, so you must change you URL to this format:
http://192.168.1.108:88/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=xxxx&pwd=xxxx

like in this example:
http://gc8883.myfoscam.org:20070/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=user&pwd=user

If you want "stream like" view, enable AutoRefresh with 1s timeout ;-)
