### ISSUE TITLE
How to use The database

### ISSUE THREAD

**Issue by Miladniaz** [TomasValenta/WebCamViewer#43]
Hello I want to use the database and add more new live cams to the app how can i use it.

**Comment by TomasValenta** [comment]
Hi,
import some cams from community database (but now contain only few live stream webcams) or watch this how to:
https://youtu.be/tAwHqEK4IpI
If you can use Wireshark, this is very good how to:
https://youtu.be/8PuUnQCS7DQ
Now I am on the holiday, but later I want add more live streams, so if you need help with some cams, send me the suggestion and I can add it after holiday to the community database ;-)

**Comment by Miladniaz** [comment]
Hi,
I want to open the database and add/remove the live cams you put into it.
Thanks

**Comment by TomasValenta** [comment]
Direct **write/modify/remove** public access for all user is not allowed, because administration of the database need some rules and responsible administrator role.

If you want to add the WebCam to the public database send the approval request (after you create the WebCam in your local database) or send me the suggestion.

If you want modify the WebCam in the public database click on something is wrong and I can research the problem (url, location, name...)

If you want remove the WebCam in the public database send me the suggestion with removal description.

(if you want reply leave in the suggestion dialog your email address).

But to your local database you can add **everything** without any approval!
